[package]
name = "ros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.7"
lazy_static = { version = "1", features = ["spin_no_std"] }


[workspace]
members = ['xtask', '']
default-members = ['xtask', '']
