[target.riscv64imac-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", "-Cforce-frame-pointers=yes"
]

[alias]
xtask = "run --package xtask --"
make = "xtask make"
qemu = "xtask qemu"
debug = "xtask debug"
test_kernel = "xtask test"
